import { prisma } from '../src/lib/prisma';

async function main() {
  console.log('🚀 Seeding Section 3 Summary Completion (Box) Test...');

  const testId = "summary-box-3";

  // Clean up existing
  await prisma.readingQuestion.deleteMany({
    where: { readingTestId: testId }
  });
  await prisma.readingTest.deleteMany({
    where: { id: testId }
  });

  await prisma.readingTest.create({
    data: {
      id: testId,
      title: "Summary Completion (Box): The Urban Heat Island Effect",
      section: 3,
      difficulty: "Hard",
      passage: `
        <h2>The Urban Heat Island Effect: Causes and Mitigation Strategies</h2>
        <p>As the global population increasingly gravitates toward urban centers, the phenomenon known as the Urban Heat Island (UHI) effect has become a critical concern for city planners and environmental scientists alike. An urban heat island is a metropolitan area that is significantly warmer than its surrounding rural regions, with temperature differences often reaching as much as 10 to 12 degrees Celsius during the night. This disparity is not merely a matter of localized discomfort; it has profound implications for public health, energy consumption, and the overall ecological footprint of the city.</p>
        <p>The primary cause of the UHI effect is the alteration of the land surface. In rural areas, vegetation and soil provide natural cooling through the process of evapotranspiration, where plants release moisture into the air. In contrast, urban environments are dominated by impervious surfaces such as asphalt, concrete, and brick. These materials have a high 'thermal mass,' meaning they absorb and store vast amounts of solar radiation during the day and gradually release it as heat after the sun sets. Furthermore, the 'canyon effect'—where tall buildings trap heat between their walls and prevent it from escaping into the upper atmosphere—amplifies the warming. This is compounded by 'anthropogenic heat,' the thermal energy generated by human activities such as air conditioning, industrial processes, and vehicular traffic.</p>
        <p>Mitigating the UHI effect requires a multi-faceted approach that integrates green infrastructure with innovative building materials. One of the most effective strategies is the implementation of 'cool roofs' and 'cool pavements.' These surfaces are treated with reflective coatings that have a high solar reflectance, or albedo, which bounces sunlight back into space rather than absorbing it. Another vital strategy is the expansion of urban forestry. Planting trees along streets and in parks not only provides direct shade but also restores the cooling benefits of evapotranspiration. 'Green roofs'—rooftops covered in living vegetation—offer a similar benefit, acting as a natural insulation layer that reduces the need for artificial cooling inside buildings.</p>
        <p>The successful reduction of urban temperatures offers significant economic and social rewards. Lower ambient temperatures lead to a decreased demand for electricity, particularly during peak summer months, which in turn reduces the greenhouse gas emissions associated with power generation. From a public health perspective, mitigating the UHI effect can save lives, especially among vulnerable populations such as the elderly, who are most at risk during extreme heat events. Ultimately, the challenge of the urban heat island is a challenge of design. By reimagining our cities as living ecosystems rather than concrete jungles, we can create urban environments that are not only cooler but also more resilient and sustainable for future generations.</p>
      `,
      questions: {
        create: [
          // Questions 1-7: Summary Completion with a box of options
          {
            id: "s3-sb-q1",
            type: "summary_completion",
            order: 1,
            text: "The Urban Heat Island (UHI) effect describes the [GAP] between city temperatures and those in rural areas.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["A"]
          },
          {
            id: "s3-sb-q2",
            type: "summary_completion",
            order: 2,
            text: "This warming is largely due to the replacement of [GAP] with impervious materials like concrete.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["C"]
          },
          {
            id: "s3-sb-q3",
            type: "summary_completion",
            order: 3,
            text: "These urban materials are known for their significant [GAP] of solar energy throughout the day.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["D"]
          },
          {
            id: "s3-sb-q4",
            type: "summary_completion",
            order: 4,
            text: "Additionally, heat is produced by [GAP] sources like cars and industrial machinery.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["F"]
          },
          {
            id: "s3-sb-q5",
            type: "summary_completion",
            order: 5,
            text: "To combat this, 'cool roofs' are designed so that more sunlight is [GAP] rather than stored.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["E"]
          },
          {
            id: "s3-sb-q6",
            type: "summary_completion",
            order: 6,
            text: "Health risks can be lowered, particularly for the [GAP] population during heatwaves.",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["H"]
          },
          {
            id: "s3-sb-q7",
            type: "summary_completion",
            order: 7,
            text: "The writer concludes that solving the UHI effect is primarily a matter of better [GAP].",
            options: ["A. Disparity", "B. Humidity", "C. Vegetation", "D. Absorption", "E. Reflected", "F. Anthropogenic", "G. Design", "H. Elderly"],
            answer: ["G"]
          },
          // Questions 8-14: Multiple Choice (Standard)
          {
            id: "s3-sb-q8",
            type: "multiple_choice",
            order: 8,
            text: "What is the maximum temperature difference often recorded between cities and rural areas at night?",
            options: [
              "A. 2 to 4 degrees Celsius.",
              "B. 5 to 8 degrees Celsius.",
              "C. 10 to 12 degrees Celsius.",
              "D. Over 15 degrees Celsius."
            ],
            answer: ["C"]
          },
          {
            id: "s3-sb-q9",
            type: "multiple_choice",
            order: 9,
            text: "What is the natural cooling process used by plants called?",
            options: [
              "A. Photosynthesis.",
              "B. Evapotranspiration.",
              "C. Thermal mass.",
              "D. Albedo effect."
            ],
            answer: ["B"]
          },
          {
            id: "s3-sb-q10",
            type: "multiple_choice",
            order: 10,
            text: "The 'canyon effect' is caused by:",
            options: [
              "A. Deep cracks in the city pavements.",
              "B. Heat being trapped between tall buildings.",
              "C. The use of air conditioning in skyscrapers.",
              "D. The lack of subterranean drainage systems."
            ],
            answer: ["B"]
          },
          {
            id: "s3-sb-q11",
            type: "multiple_choice",
            order: 11,
            text: "Which term describes a material's solar reflectance?",
            options: [
              "A. Thermal mass.",
              "B. Anthropogenic.",
              "C. Albedo.",
              "D. Impervious."
            ],
            answer: ["C"]
          },
          {
            id: "s3-sb-q12",
            type: "multiple_choice",
            order: 12,
            text: "How do 'green roofs' help buildings?",
            options: [
              "A. By producing solar power for the residents.",
              "B. By acting as a natural insulation layer.",
              "C. By reflecting 100% of the sunlight back to space.",
              "D. By increasing the building's thermal mass."
            ],
            answer: ["B"]
          },
          {
            id: "s3-sb-q13",
            type: "multiple_choice",
            order: 13,
            text: "Reducing urban temperatures also helps the environment by:",
            options: [
              "A. Increasing the demand for cars.",
              "B. Lowering greenhouse gas emissions from power plants.",
              "C. Promoting the use of asphalt over concrete.",
              "D. Encouraging the growth of concrete jungles."
            ],
            answer: ["B"]
          },
          {
            id: "s3-sb-q14",
            type: "multiple_choice",
            order: 14,
            text: "The writer suggests that cities should be reimagined as:",
            options: [
              "A. Industrial hubs.",
              "B. Concrete jungles.",
              "C. Living ecosystems.",
              "D. Vertical villages."
            ],
            answer: ["C"]
          }
        ]
      }
    }
  });

  console.log('✅ Section 3 Summary (Box) seeded successfully!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
